name: realtime4DGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - pretty_errors
  - python=3.8
  - pip=22.3.1
  - tqdm
  - ninja=1.11.1
  - jupyter
  - notebook